### PR TITLE
rocAL - External source reader

### PR DESCRIPTION
**Pull request by SundarRajan98**
Added 3 Modes for external source reader whose sources varies accordingly :
• Mode 0 - File Names
• Mode 1 - Raw Buffer
• Mode 2 - Decoded Buffer
• Added C++ and python examples for all 3 modes

### CODE REVIEW

**Comment by hansely** [comment]
1. The PR is building fine on my machine except that there was a half.hpp file missing error which Kiriti is currently looking into. I had to manually copy and paste the half.hpp file to the build directory for temporary fix. 
2. Regarding boost, I've verified that the boost PR has been incorporated into the PR and looks good to me. 
3. For the testing, I've built and ran the test code provided in the PR and the test works fine.

It looks like the rocalJpegExternalFileSource() is taking folderpath as input. How is it different from original rocalJpegFileSource()? 
I thought the api was implemented to support file based approach instead of folder. 
Should the users be calling rocalExternalSourceFeedInput() function for file based(names/raw buffers/decoded buffer) approach?

**Comment by kiritigowda** [comment]
Closed due to moving to rocm

**Comment by kiritigowda** [comment]
Reopen

**Comment by kiritigowda** [comment]
@SundarRajan98 can you reopen this PR for rocm/rocAL

**Comment by SundarRajan98** [comment]
@kiritigowda Reopening the PR automatically closes the PR again. After the RoCM reorganization change, I'm unable to create PRs to rocAL repo from my fork.

**Comment by hansely** [comment]
> 1. The PR is building fine on my machine except that there was a half.hpp file missing error which Kiriti is currently looking into. I had to manually copy and paste the half.hpp file to the build directory for temporary fix.
> 2. Regarding boost, I've verified that the boost PR has been incorporated into the PR and looks good to me.
> 3. For the testing, I've built and ran the test code provided in the PR and the test works fine.
> 
> It looks like the rocalJpegExternalFileSource() is taking folderpath as input. How is it different from original rocalJpegFileSource()? I thought the api was implemented to support file based approach instead of folder. Should the users be calling rocalExternalSourceFeedInput() function for file based(names/raw buffers/decoded buffer) approach?

@SundarRajan28 When you have time, would you be able to answer above questions?

**Comment by hansely** [comment]
1. 
@SundarRajan28 
> The rocALJpegExternalSource is still using file names as input. 

Did you mean folderpath?


2.
> The folder path is present in the API to be similar to other decoder APIs and not used in the external source reader. In the C++ example we added, in mode 0, we read all file names in the folder passed from user and pass the list as argument to rocalExternalSourceFeedInput.

@rrawther  
Do we want the external source reader to take _folderpath_ as an argument? 
Can't we just use rocalJpegFileSource to read the file names in the folder?

**Comment by SundarRajan98** [comment]
1. I meant to say that even though the folder path is passed to the API, its not used and only the file names passed via rocalExternalSourceFeedInput is used for external source reader.

**Comment by SundarRajan98** [comment]
@hansely I have removed the folder path argument from rocalJpegExternalFileSource API. You can check the new PR changes [here](https://github.com/ROCm/rocAL/pull/83)

**Pull request closed without merging**
