### PR TITLE
Fixing HIP CMake issue

### PR DESCRIPTION
**Pull request by SundarRajan28**
Setting AMDGPU_TARGETS before find_package(HIP) call - fixes HIP issues

### CODE REVIEW

**Comment by LakshmiKumar23** [comment]
@SundarRajan28 same comment as mentioned in MIVisionX. We cannot add this to top level. It is used to set audio flag, but #156 resolves that altogether. Please remove from this file

**Review by rrawther — APPROVED** [review]

**Comment by LakshmiKumar23** [comment]
@kiritigowda @SundarRajan28 I have made the required changes in [PR156 ]( #156 )itself. Let us close this PR

**Comment by rrawther** [comment]
this should be closed after merging 156 (incorporated in that)

**Comment by SundarRajan28** [comment]
Closing this PR since the change is added in PR #156

**Pull request closed without merging**
