### PR TITLE
PyBind - Packaging and CTests

### PR DESCRIPTION
**Pull request by kiritigowda**
* rocAL PyBind packaged into runtime package
* rocALL Pybind tests packaged into test package

### Verify rocAL PyBind with rocal-test package

Test package will install ctest module to test rocAL PyBindings. Follow below steps to test package install

```shell
mkdir rocal-pybind-test && cd rocal-pybind-test
cmake /opt/rocm/share/rocal/test/pybind
ctest -VV
```
>[!NOTE]
> * Make sure all rocAL required libraries are in your PATH
> ```shell
> export PATH=$PATH:/opt/rocm/bin
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm/lib
> export PYTHONPATH=/opt/rocm/lib:$PYTHONPATH
> ```

### CODE REVIEW

**Comment by kiritigowda** [comment]
PyBind Test CMakeLists

```
cmake /opt/rocm/share/rocal/test/pybind/
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- rocal-pybind-test: rocAL Pybind found at /opt/rocm/lib/amd/rocal
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kiriti/develop/rocal/rocal-kiriti/test
```

**Comment by kiritigowda** [comment]
CTest Logs

```
ctest  -VV
UpdateCTestConfiguration  from :/home/kiriti/develop/rocal/rocal-kiriti/test/DartConfiguration.tcl
Parse Config file:/home/kiriti/develop/rocal/rocal-kiriti/test/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/kiriti/develop/rocal/rocal-kiriti/test/DartConfiguration.tcl
Parse Config file:/home/kiriti/develop/rocal/rocal-kiriti/test/DartConfiguration.tcl
Test project /home/kiriti/develop/rocal/rocal-kiriti/test
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: rocal_pybind_test_decoders

1: Test command: /usr/bin/python3.10 "/opt/rocm/share/rocal/test/pybind/decoders_test.py"
1: Environment variables: 
1:  PYTHONPATH=/opt/rocm/lib:$PYTHONPATH
1: Test timeout computed to be: 1500
1: rocAL PyBind Decoders
1: ('audio', <function audio at 0x7fcd687330a0>)
1: ('image', <function image at 0x7fcd97c8aef0>)
1: ('image_random_crop', <function image_random_crop at 0x7fcd68732f80>)
1: ('image_raw', <function image_raw at 0x7fcd97c8b130>)
1: ('image_slice', <function image_slice at 0x7fcd68733010>)
1/6 Test #1: rocal_pybind_test_decoders .......   Passed    0.99 sec
test 2
    Start 2: rocal_pybind_test_functions

2: Test command: /usr/bin/python3.10 "/opt/rocm/share/rocal/test/pybind/functions_test.py"
2: Environment variables: 
2:  PYTHONPATH=/opt/rocm/lib:$PYTHONPATH
2: Test timeout computed to be: 1500
2: rocAL PyBind Functions
2: ('blend', <function blend at 0x7782c9d8ee60>)
2: ('blur', <function blur at 0x77829a790790>)
2: ('box_encoder', <function box_encoder at 0x77829a7915a0>)
2: ('box_iou_matcher', <function box_iou_matcher at 0x77829a791870>)
2: ('brightness', <function brightness at 0x77829a7905e0>)
2: ('brightness_fixed', <function brightness_fixed at 0x77829a790670>)
2: ('center_crop', <function center_crop at 0x77829a791240>)
2: ('color_temp', <function color_temp at 0x77829a791630>)
2: ('color_twist', <function color_twist at 0x77829a791360>)
2: ('contrast', <function contrast at 0x77829a790820>)
2: ('copy', <function copy at 0x77829a791750>)
2: ('crop', <function crop at 0x77829a7912d0>)
2: ('crop_mirror_normalize', <function crop_mirror_normalize at 0x77829a7911b0>)
2: ('exposure', <function exposure at 0x77829a790430>)
2: ('external_source', <function external_source at 0x77829a791900>)
2: ('fish_eye', <function fish_eye at 0x77829a7904c0>)
2: ('flip', <function flip at 0x77829a7908b0>)
2: ('fog', <function fog at 0x77829a790550>)
2: ('gamma_correction', <function gamma_correction at 0x77829a790940>)
2: ('hue', <function hue at 0x77829a7909d0>)
2: ('jitter', <function jitter at 0x77829a790a60>)
2: ('lens_correction', <function lens_correction at 0x77829a790700>)
2: ('mel_filter_bank', <function mel_filter_bank at 0x77829a791ea0>)
2: ('nonsilent_region', <function nonsilent_region at 0x77829a791cf0>)
2: ('nop', <function nop at 0x77829a7916c0>)
2: ('normalize', <function normalize at 0x77829a791e10>)
2: ('one_hot', <function one_hot at 0x77829a791510>)
2: ('pixelate', <function pixelate at 0x77829a790af0>)
2: ('preemphasis_filter', <function preemphasis_filter at 0x77829a791990>)
2: ('rain', <function rain at 0x77829a790b80>)
2: ('random_bbox_crop', <function random_bbox_crop at 0x77829a791480>)
2: ('random_crop', <function random_crop at 0x77829a790e50>)
2: ('resample', <function resample at 0x77829a791b40>)
2: ('resize', <function resize at 0x77829a790c10>)
2: ('resize_crop', <function resize_crop at 0x77829a790d30>)
2: ('resize_crop_mirror', <function resize_crop_mirror at 0x77829a790ca0>)
2: ('resize_mirror_normalize', <function resize_mirror_normalize at 0x77829a790dc0>)
2: ('rotate', <function rotate at 0x77829a790ee0>)
2: ('saturation', <function saturation at 0x77829a790f70>)
2: ('slice', <function slice at 0x77829a791d80>)
2: ('snow', <function snow at 0x77829a7903a0>)
2: ('snp_noise', <function snp_noise at 0x77829a7917e0>)
2: ('spectrogram', <function spectrogram at 0x77829a791a20>)
2: ('ssd_random_crop', <function ssd_random_crop at 0x77829a791000>)
2: ('tensor_add_tensor_float', <function tensor_add_tensor_float at 0x77829a791bd0>)
2: ('tensor_mul_scalar_float', <function tensor_mul_scalar_float at 0x77829a791c60>)
2: ('to_decibels', <function to_decibels at 0x77829a791ab0>)
2: ('uniform', <function uniform at 0x77829a7913f0>)
2: ('vignette', <function vignette at 0x77829a791120>)
2: ('warp_affine', <function warp_affine at 0x77829a791090>)
2/6 Test #2: rocal_pybind_test_functions ......   Passed    0.17 sec
test 3
    Start 3: rocal_pybind_test_pipelines

3: Test command: /usr/bin/python3.10 "/opt/rocm/share/rocal/test/pybind/pipelines_test.py"
3: Environment variables: 
3:  PYTHONPATH=/opt/rocm/lib:$PYTHONPATH
3: Test timeout computed to be: 1500
3: rocAL PyBind Pipelines
3: ('__enter__', <function Pipeline.__enter__ at 0x789dcdb01990>)
3: ('__exit__', <function Pipeline.__exit__ at 0x789dcdb01a20>)
3: ('__init__', <function Pipeline.__init__ at 0x789dcdb01510>)
3: ('build', <function Pipeline.build at 0x789dcdb015a0>)
3: ('copyToExternalTensor', <function Pipeline.copyToExternalTensor at 0x789dcdb017e0>)
3: ('copy_encoded_boxes_and_lables', <function Pipeline.copy_encoded_boxes_and_lables at 0x789dcdb02320>)
3: ('define_graph', <function Pipeline.define_graph at 0x789dcdb016c0>)
3: ('get_bounding_box_cords', <function Pipeline.get_bounding_box_cords at 0x789dcdb020e0>)
3: ('get_bounding_box_count', <function Pipeline.get_bounding_box_count at 0x789dcdb01fc0>)
3: ('get_bounding_box_labels', <function Pipeline.get_bounding_box_labels at 0x789dcdb02050>)
3: ('get_encoded_boxes_and_lables', <function Pipeline.get_encoded_boxes_and_lables at 0x789dcdb023b0>)
3: ('get_handle', <function Pipeline.get_handle at 0x789dcdb01750>)
3: ('get_image_id', <function Pipeline.get_image_id at 0x789dcdb01f30>)
3: ('get_image_labels', <function Pipeline.get_image_labels at 0x789dcdb02290>)
3: ('get_image_name', <function Pipeline.get_image_name at 0x789dcdb01ea0>)
3: ('get_image_name_length', <function Pipeline.get_image_name_length at 0x789dcdb02560>)
3: ('get_img_sizes', <function Pipeline.get_img_sizes at 0x789dcdb02440>)
3: ('get_last_batch_padded_size', <function Pipeline.get_last_batch_padded_size at 0x789dcdb029e0>)
3: ('get_mask_coordinates', <function Pipeline.get_mask_coordinates at 0x789dcdb02200>)
3: ('get_mask_count', <function Pipeline.get_mask_count at 0x789dcdb02170>)
3: ('get_matched_indices', <function Pipeline.get_matched_indices at 0x789dcdb028c0>)
3: ('get_one_hot_encoded_labels', <function Pipeline.get_one_hot_encoded_labels at 0x789dcdb01870>)
3: ('get_output_tensors', <function Pipeline.get_output_tensors at 0x789dcdb02950>)
3: ('get_remaining_images', <function Pipeline.get_remaining_images at 0x789dcdb025f0>)
3: ('get_roi_img_sizes', <function Pipeline.get_roi_img_sizes at 0x789dcdb024d0>)
3: ('is_empty', <function Pipeline.is_empty at 0x789dcdb027a0>)
3: ('rocal_release', <function Pipeline.rocal_release at 0x789dcdb02680>)
3: ('rocal_reset_loaders', <function Pipeline.rocal_reset_loaders at 0x789dcdb02710>)
3: ('rocal_run', <function Pipeline.rocal_run at 0x789dcdb01630>)
3: ('run', <function Pipeline.run at 0x789dcdb02a70>)
3: ('set_outputs', <function Pipeline.set_outputs at 0x789dcdb01900>)
3: ('set_seed', <function Pipeline.set_seed at 0x789dcdb01ab0>)
3: ('timing_info', <function Pipeline.timing_info at 0x789dcdb02830>)
3/6 Test #3: rocal_pybind_test_pipelines ......   Passed    0.16 sec
test 4
    Start 4: rocal_pybind_test_randoms

4: Test command: /usr/bin/python3.10 "/opt/rocm/share/rocal/test/pybind/randoms_test.py"
4: Environment variables: 
4:  PYTHONPATH=/opt/rocm/lib:$PYTHONPATH
4: Test timeout computed to be: 1500
4: rocAL PyBind Randoms
4: ('coin_flip', <function coin_flip at 0x75085658a440>)
4: ('normal', <function normal at 0x7508277d2cb0>)
4: ('uniform', <function uniform at 0x75085658a8c0>)
4/6 Test #4: rocal_pybind_test_randoms ........   Passed    0.17 sec
test 5
    Start 5: rocal_pybind_test_readers

5: Test command: /usr/bin/python3.10 "/opt/rocm/share/rocal/test/pybind/readers_test.py"
5: Environment variables: 
5:  PYTHONPATH=/opt/rocm/lib:$PYTHONPATH
5: Test timeout computed to be: 1500
5: rocAL PyBind Readers
5: ('caffe', <function caffe at 0x7914c793eef0>)
5: ('caffe2', <function caffe2 at 0x7914c793ef80>)
5: ('coco', <function coco at 0x7914f668a440>)
5: ('file', <function file at 0x7914f668ab00>)
5: ('mxnet', <function mxnet at 0x7914c793f1c0>)
5: ('sequence_reader', <function sequence_reader at 0x7914c793f130>)
5: ('tfrecord', <function tfrecord at 0x7914c793ee60>)
5: ('video', <function video at 0x7914c793f010>)
5: ('video_resize', <function video_resize at 0x7914c793f0a0>)
5/6 Test #5: rocal_pybind_test_readers ........   Passed    0.17 sec
test 6
    Start 6: rocal_pybind_test_types

6: Test command: /usr/bin/python3.10 "/opt/rocm/share/rocal/test/pybind/types_test.py"
6: Environment variables: 
6:  PYTHONPATH=/opt/rocm/lib:$PYTHONPATH
6: Test timeout computed to be: 1500
6: rocAL PyBind Types
6: ('data_type_function', <function data_type_function at 0x79bfc5a8a0e0>)
6/6 Test #6: rocal_pybind_test_types ..........   Passed    0.10 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) =   1.77 sec

```

**Comment by kiritigowda** [comment]
@AryanSalmanpour this PR supports package install of pybind components. With this you will have all pybind functionality installed with apt install rocal. To use the pybind module set `PYTHONPATH=/opt/rocm/lib:$PYTHONPATH`.

**Comment by kiritigowda** [comment]
@rrawther & @LakshmiKumar23 -- issue #220 needs to be fixed to add full functionality test in ctest for devOps

**Comment by LakshmiKumar23** [comment]
tests passing on docker. Can be merged

root@kapu:~/rocal-test# ctest -VV
UpdateCTestConfiguration  from :/root/rocal-test/DartConfiguration.tcl
Parse Config file:/root/rocal-test/DartConfiguration.tcl
UpdateCTestConfiguration  from :/root/rocal-test/DartConfiguration.tcl
Parse Config file:/root/rocal-test/DartConfiguration.tcl
Test project /root/rocal-test
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: rocal_pybind_test_decoders

1: Test command: /usr/bin/python3.10 "/opt/rocm/share/rocal/test/pybind/decoders_test.py"
1: Working Directory: /root/rocal-test
1: Environment variables:
1:  PYTHONPATH=/opt/rocm/lib:$PYTHONPATH
1: Test timeout computed to be: 1500
1: rocAL PyBind Decoders
1: ('audio', <function audio at 0x7c0413d56d40>)
1: ('image', <function image at 0x7c0467963a30>)
1: ('image_random_crop', <function image_random_crop at 0x7c0467963b50>)
1: ('image_raw', <function image_raw at 0x7c0467963be0>)
1: ('image_slice', <function image_slice at 0x7c0413d56cb0>)
1/6 Test #1: rocal_pybind_test_decoders .......   Passed    0.79 sec
test 2
    Start 2: rocal_pybind_test_functions

2: Test command: /usr/bin/python3.10 "/opt/rocm/share/rocal/test/pybind/functions_test.py"
2: Working Directory: /root/rocal-test
2: Environment variables:
2:  PYTHONPATH=/opt/rocm/lib:$PYTHONPATH
2: Test timeout computed to be: 1500
2: rocAL PyBind Functions
2: ('blend', <function blend at 0x708700d2fb50>)
2: ('blur', <function blur at 0x7086ad167f40>)
2: ('box_encoder', <function box_encoder at 0x7086ad16cdc0>)
2: ('box_iou_matcher', <function box_iou_matcher at 0x7086ad16d090>)
2: ('brightness', <function brightness at 0x7086ad167d90>)
2: ('brightness_fixed', <function brightness_fixed at 0x7086ad167e20>)
2: ('center_crop', <function center_crop at 0x7086ad16ca60>)
2: ('color_temp', <function color_temp at 0x7086ad16ce50>)
2: ('color_twist', <function color_twist at 0x7086ad16cb80>)
2: ('contrast', <function contrast at 0x7086ad16c040>)
2: ('copy', <function copy at 0x7086ad16cf70>)
2: ('crop', <function crop at 0x7086ad16caf0>)
2: ('crop_mirror_normalize', <function crop_mirror_normalize at 0x7086ad16c9d0>)
2: ('exposure', <function exposure at 0x7086ad167be0>)
2: ('external_source', <function external_source at 0x7086ad16d120>)
2: ('fish_eye', <function fish_eye at 0x7086ad167c70>)
2: ('flip', <function flip at 0x7086ad16c0d0>)
2: ('fog', <function fog at 0x7086ad167d00>)
2: ('gamma_correction', <function gamma_correction at 0x7086ad16c160>)
2: ('hue', <function hue at 0x7086ad16c1f0>)
2: ('jitter', <function jitter at 0x7086ad16c280>)
2: ('lens_correction', <function lens_correction at 0x7086ad167eb0>)
2: ('mel_filter_bank', <function mel_filter_bank at 0x7086ad16d6c0>)
2: ('nonsilent_region', <function nonsilent_region at 0x7086ad16d510>)
2: ('nop', <function nop at 0x7086ad16cee0>)
2: ('normalize', <function normalize at 0x7086ad16d630>)
2: ('one_hot', <function one_hot at 0x7086ad16cd30>)
2: ('pixelate', <function pixelate at 0x7086ad16c310>)
2: ('preemphasis_filter', <function preemphasis_filter at 0x7086ad16d1b0>)
2: ('rain', <function rain at 0x7086ad16c3a0>)
2: ('random_bbox_crop', <function random_bbox_crop at 0x7086ad16cca0>)
2: ('random_crop', <function random_crop at 0x7086ad16c670>)
2: ('resample', <function resample at 0x7086ad16d360>)
2: ('resize', <function resize at 0x7086ad16c430>)
2: ('resize_crop', <function resize_crop at 0x7086ad16c550>)
2: ('resize_crop_mirror', <function resize_crop_mirror at 0x7086ad16c4c0>)
2: ('resize_mirror_normalize', <function resize_mirror_normalize at 0x7086ad16c5e0>)
2: ('rotate', <function rotate at 0x7086ad16c700>)
2: ('saturation', <function saturation at 0x7086ad16c790>)
2: ('slice', <function slice at 0x7086ad16d5a0>)
2: ('snow', <function snow at 0x7086ad167b50>)
2: ('snp_noise', <function snp_noise at 0x7086ad16d000>)
2: ('spectrogram', <function spectrogram at 0x7086ad16d240>)
2: ('ssd_random_crop', <function ssd_random_crop at 0x7086ad16c820>)
2: ('tensor_add_tensor_float', <function tensor_add_tensor_float at 0x7086ad16d3f0>)
2: ('tensor_mul_scalar_float', <function tensor_mul_scalar_float at 0x7086ad16d480>)
2: ('to_decibels', <function to_decibels at 0x7086ad16d2d0>)
2: ('uniform', <function uniform at 0x7086ad16cc10>)
2: ('vignette', <function vignette at 0x7086ad16c940>)
2: ('warp_affine', <function warp_affine at 0x7086ad16c8b0>)
2/6 Test #2: rocal_pybind_test_functions ......   Passed    0.45 sec
test 3
    Start 3: rocal_pybind_test_pipelines

3: Test command: /usr/bin/python3.10 "/opt/rocm/share/rocal/test/pybind/pipelines_test.py"
3: Working Directory: /root/rocal-test
3: Environment variables:
3:  PYTHONPATH=/opt/rocm/lib:$PYTHONPATH
3: Test timeout computed to be: 1500
3: rocAL PyBind Pipelines
3: ('__enter__', <function Pipeline.__enter__ at 0x758e0474d630>)
3: ('__exit__', <function Pipeline.__exit__ at 0x758e0474d6c0>)
3: ('__init__', <function Pipeline.__init__ at 0x758e0474d1b0>)
3: ('build', <function Pipeline.build at 0x758e0474d240>)
3: ('copyToExternalTensor', <function Pipeline.copyToExternalTensor at 0x758e0474d480>)
3: ('copy_encoded_boxes_and_lables', <function Pipeline.copy_encoded_boxes_and_lables at 0x758e0474dfc0>)
3: ('define_graph', <function Pipeline.define_graph at 0x758e0474d360>)
3: ('get_bounding_box_cords', <function Pipeline.get_bounding_box_cords at 0x758e0474dd80>)
3: ('get_bounding_box_count', <function Pipeline.get_bounding_box_count at 0x758e0474dc60>)
3: ('get_bounding_box_labels', <function Pipeline.get_bounding_box_labels at 0x758e0474dcf0>)
3: ('get_encoded_boxes_and_lables', <function Pipeline.get_encoded_boxes_and_lables at 0x758e0474e050>)
3: ('get_handle', <function Pipeline.get_handle at 0x758e0474d3f0>)
3: ('get_image_id', <function Pipeline.get_image_id at 0x758e0474dbd0>)
3: ('get_image_labels', <function Pipeline.get_image_labels at 0x758e0474df30>)
3: ('get_image_name', <function Pipeline.get_image_name at 0x758e0474db40>)
3: ('get_image_name_length', <function Pipeline.get_image_name_length at 0x758e0474e200>)
3: ('get_img_sizes', <function Pipeline.get_img_sizes at 0x758e0474e0e0>)
3: ('get_last_batch_padded_size', <function Pipeline.get_last_batch_padded_size at 0x758e0474e680>)
3: ('get_mask_coordinates', <function Pipeline.get_mask_coordinates at 0x758e0474dea0>)
3: ('get_mask_count', <function Pipeline.get_mask_count at 0x758e0474de10>)
3: ('get_matched_indices', <function Pipeline.get_matched_indices at 0x758e0474e560>)
3: ('get_one_hot_encoded_labels', <function Pipeline.get_one_hot_encoded_labels at 0x758e0474d510>)
3: ('get_output_tensors', <function Pipeline.get_output_tensors at 0x758e0474e5f0>)
3: ('get_remaining_images', <function Pipeline.get_remaining_images at 0x758e0474e290>)
3: ('get_roi_img_sizes', <function Pipeline.get_roi_img_sizes at 0x758e0474e170>)
3: ('is_empty', <function Pipeline.is_empty at 0x758e0474e440>)
3: ('rocal_release', <function Pipeline.rocal_release at 0x758e0474e320>)
3: ('rocal_reset_loaders', <function Pipeline.rocal_reset_loaders at 0x758e0474e3b0>)
3: ('rocal_run', <function Pipeline.rocal_run at 0x758e0474d2d0>)
3: ('run', <function Pipeline.run at 0x758e0474e710>)
3: ('set_outputs', <function Pipeline.set_outputs at 0x758e0474d5a0>)
3: ('set_seed', <function Pipeline.set_seed at 0x758e0474d750>)
3: ('timing_info', <function Pipeline.timing_info at 0x758e0474e4d0>)
3/6 Test #3: rocal_pybind_test_pipelines ......   Passed    0.45 sec
test 4
    Start 4: rocal_pybind_test_randoms

4: Test command: /usr/bin/python3.10 "/opt/rocm/share/rocal/test/pybind/randoms_test.py"
4: Working Directory: /root/rocal-test
4: Environment variables:
4:  PYTHONPATH=/opt/rocm/lib:$PYTHONPATH
4: Test timeout computed to be: 1500
4: rocAL PyBind Randoms
4: ('coin_flip', <function coin_flip at 0x7a6161f4ba30>)
4: ('normal', <function normal at 0x7a6161f4bac0>)
4: ('uniform', <function uniform at 0x7a6161f4bb50>)
4/6 Test #4: rocal_pybind_test_randoms ........   Passed    0.46 sec
test 5
    Start 5: rocal_pybind_test_readers

5: Test command: /usr/bin/python3.10 "/opt/rocm/share/rocal/test/pybind/readers_test.py"
5: Working Directory: /root/rocal-test
5: Environment variables:
5:  PYTHONPATH=/opt/rocm/lib:$PYTHONPATH
5: Test timeout computed to be: 1500
5: rocAL PyBind Readers
5: ('caffe', <function caffe at 0x7cc390556b00>)
5: ('caffe2', <function caffe2 at 0x7cc390556b90>)
5: ('coco', <function coco at 0x7cc3e41e7ac0>)
5: ('file', <function file at 0x7cc3e41e7be0>)
5: ('mxnet', <function mxnet at 0x7cc390556dd0>)
5: ('sequence_reader', <function sequence_reader at 0x7cc390556d40>)
5: ('tfrecord', <function tfrecord at 0x7cc3e41e7b50>)
5: ('video', <function video at 0x7cc390556c20>)
5: ('video_resize', <function video_resize at 0x7cc390556cb0>)
5/6 Test #5: rocal_pybind_test_readers ........   Passed    0.46 sec
test 6
    Start 6: rocal_pybind_test_types

6: Test command: /usr/bin/python3.10 "/opt/rocm/share/rocal/test/pybind/types_test.py"
6: Working Directory: /root/rocal-test
6: Environment variables:
6:  PYTHONPATH=/opt/rocm/lib:$PYTHONPATH
6: Test timeout computed to be: 1500
6: rocAL PyBind Types
6: ('data_type_function', <function data_type_function at 0x7681182079a0>)
6/6 Test #6: rocal_pybind_test_types ..........   Passed    0.31 sec

100% tests passed, 0 tests failed out of 6

Total Test time (real) =   2.92 sec

**Review by LakshmiKumar23 — APPROVED** [review]

**Pull request merged**
