### PR TITLE
Fix GPU pipeline errors wrt AMD Clang++

### PR DESCRIPTION
**Pull request by fiona-gladwin**
- Set graph and context affinity group and reserved to 0, to avoid corruption of values.
- Fixes GPU pipeline errors, which lead to OpenVX errors

### CODE REVIEW

**Review by rrawther — APPROVED** [review]

**Review by kiritigowda — APPROVED** [review]

**Comment by kiritigowda** [comment]
@fiona-gladwin @rrawther - need updates to trickle down to CI before this can be merged

**Comment by kiritigowda** [comment]
With Fix
```
ctest
Test project /home/kiriti/develop/rocal-kiriti/test
      Start  1: basic_test_cpu
 1/14 Test  #1: basic_test_cpu .....................   Passed    4.02 sec
      Start  2: basic_test_gpu
 2/14 Test  #2: basic_test_gpu .....................   Passed    0.69 sec
      Start  3: basic_test_gray
 3/14 Test  #3: basic_test_gray ....................   Passed    1.03 sec
      Start  4: basic_test_rgb
 4/14 Test  #4: basic_test_rgb .....................   Passed    1.15 sec
      Start  5: dataloader_multithread_cpu
 5/14 Test  #5: dataloader_multithread_cpu .........   Passed    5.26 sec
      Start  6: dataloader_multithread_gpu
 6/14 Test  #6: dataloader_multithread_gpu .........   Passed    5.87 sec
      Start  7: performance_tests_cpu
 7/14 Test  #7: performance_tests_cpu ..............   Passed   10.40 sec
      Start  8: performance_tests_gpu
 8/14 Test  #8: performance_tests_gpu ..............   Passed    7.05 sec
      Start  9: performance_tests_with_depth_cpu
 9/14 Test  #9: performance_tests_with_depth_cpu ...   Passed    5.49 sec
      Start 10: performance_tests_with_depth_gpu
10/14 Test #10: performance_tests_with_depth_gpu ...   Passed    2.13 sec
      Start 11: unit_tests_cpu
11/14 Test #11: unit_tests_cpu .....................   Passed   17.96 sec
      Start 12: unit_tests_gpu
12/14 Test #12: unit_tests_gpu .....................   Passed   14.57 sec
      Start 13: unit_tests_gray
13/14 Test #13: unit_tests_gray ....................   Passed    6.18 sec
      Start 14: video_tests
14/14 Test #14: video_tests ........................   Passed   86.89 sec

100% tests passed, 0 tests failed out of 14

Total Test time (real) = 168.71 sec

```

**Comment by kiritigowda** [comment]
@fiona-gladwin @rrawther 

Passing Azure CI

https://dev.azure.com/ROCm-CI/ROCm-CI/_build/results?buildId=17108&view=ms.vss-test-web.build-test-results-tab

**Comment by kiritigowda** [comment]
MIVisionX fix in mainline #15320, tests on CI require mainline package from 15320+

**Pull request merged**
