### PR TITLE
Readme - Updates

### PR DESCRIPTION
**Pull request by kiritigowda**
Fix Prereqs

### CODE REVIEW

**Comment by LakshmiKumar23** [comment]
@kiritigowda please add the readme changes to build docker `--build-arg` that we discussed and the version numbers for pybind11 in README and Setup.py

**Comment by LakshmiKumar23** [comment]
@kiritigowda Can you also change the protobuf install on dockers to use dev package. It's using a specific version now, unlike the setup script

**Comment by kiritigowda** [comment]
@LakshmiKumar23 -- please approve these changes

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 -- please approve these changes

@kiritigowda can you add the docker files changes also, only for protobuf package into this PR

**Comment by kiritigowda** [comment]
> > @LakshmiKumar23 -- please approve these changes
> 
> @kiritigowda can you add the docker files changes also, only for protobuf package into this PR

Docker changes are already merged

**Review by LakshmiKumar23 — APPROVED** [review]

**Pull request merged**
